// packages/jekyll-theme-dummy-vue/src/views/Home.vue
<template>
  <div class="home">
    <ul>
      <li v-for="post of posts" :key="post.url">
        <a :href="postUrl(post)">{{ post.title }}</a>
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  name: 'Home',
  computed: {
    posts() {
      return this.$store.state.site.posts;
    },
  },
  async mounted() {
    this.$store.dispatch('site/load');
  },
  methods: {
    postUrl(post) {
      return `${this.$store.state.site.baseurl}${post.url}`;
    },
  },
};
</script>

// packages/jekyll-theme-dummy-react/src/views/Home.js
import React, { useCallback, useMemo } from 'react';
import useMount from 'react-use/lib/useMount';
import { useStore } from '../store';

const Home = () => {
  const { state, dispatch } = useStore();
  const posts = useMemo(() => state.site?.posts || [], [state.site]);

  useMount(async () => dispatch({ type: 'site/load' }));

  const postUrl = useCallback(
    (post) => {
      if (state.site?.baseurl) {
        return `${state.site.baseurl}${post.url}`;
      }
      return post.url;
    },
    [state.site],
  );

  return (
    <div className="home">
      <ul>
        {posts.map((post) => (
          <li key={post.url}>
            <a href={postUrl(post)}>{post.title}</a>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
