// packages/jekyll-theme-dummy-vue/src/views/Home.vue
<template>
  <div class="home">
    <ul>
      <li v-for="post of posts" :key="post.url">
        <a @click="readPost(post)">{{ post.title }}</a>
      </li>
    </ul>
  </div>
</template>

<script>
import renderCanvasFavIcon from '../util/renderCanvasFavIcon';

export default {
  name: 'Home',
  computed: {
    posts() {
      return this.$store.state.site.posts;
    },
  },
  async mounted() {
    this.$store.dispatch('site/load');
    this.$store.dispatch('post/downloading');
    renderCanvasFavIcon({ width: 16, height: 16, draw: this.draw });
  },
  methods: {
    readPost(post) {
      this.$store.dispatch('route/replace', { post }).then(() => {
        this.$router.push(post.url);
      });
    },
    draw(ctx) {
      ctx.fillStyle = 'yellow';
      ctx.fillRect(0, 0, 16, 16);
    },
  },
};
</script>

// packages/jekyll-theme-dummy-react/src/views/Home.tsx
import React, { useMemo, useCallback } from 'react';
import useMount from 'react-use/lib/useMount';
import { Link } from 'react-router-dom';
import { useStore } from '../store';
import useCanvasFavIcon from '../util/useCanvasFavIcon';

type Post = {
  url: string;
  title: string;
};

const Home = () => {
  const { state, dispatch } = useStore();
  const posts = useMemo(() => state.site?.posts || [], [state.site]);

  useMount(async () => {
    dispatch({ type: 'site/load' });
    dispatch({ type: 'post/downloading' });
  });

  const draw = useCallback((ctx: CanvasRenderingContext2D) => {
    ctx.fillStyle = 'yellow';
    ctx.fillRect(0, 0, 16, 16);
  }, []);

  useCanvasFavIcon({ width: 16, height: 16, draw });

  return (
    <div className="home">
      <ul>
        {posts.map((post: Post) => (
          <li key={post.url}>
            <Link
              to={{
                pathname: post.url,
                state: {
                  post,
                },
              }}
            >
              {post.title}
            </Link>
          </li>
        ))}
      </ul>
    </div>
  );
};

export default Home;
