// packages/jekyll-theme-dummy-vue/src/views/Post.vue
<template>
  <div v-if="downloading">Downloading</div>
  <div v-else>
    <HtmlWrapper :html="content || original" />
    <Comment />
  </div>
</template>

<script>
import HtmlWrapper from '../components/html/HtmlWrapper';
import Comment from '../components/post/Comment';
import renderCanvasFavIcon from '../util/renderCanvasFavIcon';

export default {
  name: 'Post',
  components: { HtmlWrapper, Comment },
  computed: {
    vuex() {
      return this.$store.state;
    },
    downloading() {
      return this.$store.state.post.downloading;
    },
    original() {
      return this.$slots.default[0].text;
    },
    content() {
      const content = this.$store.state.post.content;
      if (content) {
        const el = document.createElement('div');
        el.innerHTML = content;
        const outerHTML = el.getElementsByTagName('main')[0]?.outerHTML || '';
        el.remove();
        return outerHTML;
      }

      return '';
    },
  },
  async mounted() {
    await this.$store.dispatch('site/load');
    await this.$store.dispatch('post/downloading');
    await this.$store.dispatch('post/download', {
      post: this.$store.state.route.props.post || {
        url: this.$route.path,
      },
    });
    await this.$store.dispatch('post/downloaded');

    renderCanvasFavIcon({ width: 16, height: 16, draw: this.draw });
  },
  methods: {
    draw(ctx) {
      ctx.fillStyle = 'green';
      ctx.fillRect(0, 0, 16, 16);
    },
  },
};
</script>

// packages/jekyll-theme-dummy-react/src/views/Post.tsx
import React, { useCallback, useMemo, FunctionComponent } from 'react';
import { useLocation } from 'react-router-dom';
import useMount from 'react-use/lib/useMount';
import { useStore } from '../store';
import HtmlWrapper from '../components/html/HtmlWrapper';
import Comment from '../components/post/Comment';
import useCanvasFavIcon from '../util/useCanvasFavIcon';

type LocationState = {
  post: Object;
};

const Post: FunctionComponent = ({ children }) => {
  const { state, dispatch } = useStore();
  const location = useLocation<LocationState>();

  const load = useCallback(async () => {
    await dispatch({ type: 'site/load' });
    await dispatch({ type: 'post/downloading' });
    await dispatch({
      type: 'post/download',
      payload: {
        post: location.state?.post || {
          url: location.pathname,
        },
      },
    });
    await dispatch({ type: 'post/downloaded' });
  }, [location.state, location.pathname, dispatch]);

  useMount(() => {
    load();
  });

  const content = useMemo(() => {
    if (state.post.content) {
      const el = document.createElement('div');
      el.innerHTML = state.post.content;
      const outerHTML = el.getElementsByTagName('main')[0]?.outerHTML || '';
      el.remove();
      return outerHTML;
    }

    return '';
  }, [state.post.content]);

  const draw = useCallback((ctx) => {
    ctx.fillStyle = 'green';
    ctx.fillRect(0, 0, 16, 16);
  }, []);

  useCanvasFavIcon({ width: 16, height: 16, draw });

  if (state.post.downloading) {
    return <div>Downloading</div>;
  }

  return (
    <div>
      <HtmlWrapper html={content || children} />
      <Comment />
    </div>
  );
};

export default Post;
