// packages/jekyll-theme-dummy-vue/src/components/navigation/NavTop.vue
<template>
  <div class="NavTop">
    {{ title }}
  </div>
</template>

<script>
export default {
  name: 'NavTop',
  computed: {
    title() {
      const location = this.$route;
      if (location.path === '/') {
        return '';
      } else if (location.path.startsWith('/posts/')) {
        const post = this.$store.state.post.post;
        return (post || {}).title || '';
      }
      return '';
    },
  },
};
</script>

<style lang="scss" scoped>
@import '../../sass/styles.scss';
.NavTop {
  display: flex;
  justify-content: flex-start;
  align-items: center;
  height: 100%;
  padding-left: 1rem;
  padding-right: 1rem;
  background-color: $primaryBgColor;
  color: $primaryColor;
  border-radius: 0.25rem;
}
</style>

// packages/jekyll-theme-dummy-react/src/components/navigation/NavTop.js
import React, { useMemo } from 'react';
import { useLocation } from 'react-router-dom';
import { useStore } from '../../store';
import styles from './NavTop.module.scss';

const NavTop = () => {
  const location = useLocation();
  const { state } = useStore();
  const title = useMemo(() => {
    if (location.pathname === '/') {
      return '';
    } else if (location.pathname.startsWith('/posts/')) {
      return state.post.post?.title || '';
    }
    return '';
  }, [location, state.post]);

  return <div className={styles.NavTop}>{title}</div>;
};

export default NavTop;
