// packages/jekyll-theme-dummy-react/src/components/App.js
import React from 'react';
import NavSide from './navigation/NavSide';
import NavTop from './navigation/NavTop';
import HtmlWrapper from './html/HtmlWrapper';
import styles from './App.module.scss';

const App = ({ children }) => {
  return (
    <div className={styles.App}>
      <div className={styles.navSide}>
        <NavSide />
      </div>
      <div className={styles.container}>
        <div className={styles.navTop}>
          <NavTop />
        </div>
        <HtmlWrapper className={styles.content} html={children} />
      </div>
    </div>
  );
}

export default App;

// packages/jekyll-theme-dummy-vue/src/App.vue
<template>
  <div class="App">
    <div class="navSide">
      <NavSide />
    </div>
    <div class="container">
      <div class="navTop">
        <NavTop />
      </div>
      <div class="content">
        <HtmlWrapper :html="$slots.default[0].text" />
      </div>
    </div>
  </div>
</template>

<script>
import NavSide from './components/navigation/NavSide';
import NavTop from './components/navigation/NavTop';
import HtmlWrapper from './components/html/HtmlWrapper';

export default {
  name: 'App',
  components: {
    NavSide,
    NavTop,
    HtmlWrapper,
  },
};
</script>

<style lang="less" scoped>
.App {
  width: 100vw;
  height: 100vh;
  display: flex;
  padding: 0.5rem;
}

.navSide {
  flex: 0 0 12.5rem;
}

.container {
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  margin-left: 0.5rem;
}

.navTop {
  flex: 0 0 3.125rem;
}

.content {
  flex-grow: 1;
  flex-shrink: 1;
  overflow: scroll;
  margin-top: 0.5rem;
}
</style>
